apiVersion: v1
kind: Secret
metadata:
  name: todo-backend-secrets
type: Opaque
data:
  openrouter-api-key: c2stb3J2MTM5MmYwMzhhMjJiYjA0ZDY1MmQzYzkzYzIyMGJlZjc5N2EwNzUwMWJjNzEzMDZkYTVhYTcwYmViNDJkMWMxNTI=